In [1]:
import numpy as np

In [21]:
l =[1,2,3,4]

In [26]:
arr=np.array(l)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
l1=[[1,2,3],[4,5,6]]

In [15]:
arr1=np.asarray(l1)

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(arr1)

numpy.ndarray

In [18]:
a=[1,2,4]
np.asanyarray(a)

array([1, 2, 4])

In [22]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [25]:
type(b)

numpy.matrix

In [23]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [27]:
a= np.asanyarray(l)

In [28]:
a

array([1, 2, 3, 4])

In [29]:
c=a

In [30]:
c

array([1, 2, 3, 4])

In [31]:
c[0]=100

In [32]:
a

array([100,   2,   3,   4])

In [33]:
c

array([100,   2,   3,   4])

In [34]:
d=np.copy(c)

In [35]:
d

array([100,   2,   3,   4])

In [36]:
d[2]=45

In [37]:
d

array([100,   2,  45,   4])

In [38]:
c

array([100,   2,   3,   4])

In [41]:
np.fromfunction( lambda i,j :i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [44]:
(lambda i,j :i==j ,(3,3))

(<function __main__.<lambda>(i, j)>, (3, 3))

In [45]:
np.fromfunction( lambda i,j :i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])