In [199]:
import numpy as np

In [63]:
l =[1,2,3,4]

In [64]:
arr=np.array(l)

In [65]:
arr

array([1, 2, 3, 4])

In [66]:
type(arr)

numpy.ndarray

In [67]:
l1=[[1,2,3],[4,5,6]]

In [68]:
arr1=np.asarray(l1)

In [69]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
type(arr1)

numpy.ndarray

In [71]:
a=[1,2,4]
np.asanyarray(a)

array([1, 2, 4])

In [72]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [73]:
type(b)

numpy.matrix

In [74]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [75]:
a= np.asanyarray(l)

In [76]:
a

array([1, 2, 3, 4])

In [77]:
c=a

In [78]:
c

array([1, 2, 3, 4])

In [79]:
c[0]=100

In [80]:
a

array([100,   2,   3,   4])

In [81]:
c

array([100,   2,   3,   4])

In [82]:
d=np.copy(c)

In [83]:
d

array([100,   2,   3,   4])

In [84]:
d[2]=45

In [85]:
d

array([100,   2,  45,   4])

In [86]:
c

array([100,   2,   3,   4])

In [87]:
np.fromfunction( lambda i,j :i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [88]:
(lambda i,j :i==j ,(3,3))

(<function __main__.<lambda>(i, j)>, (3, 3))

In [89]:
np.fromfunction( lambda i,j :i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [95]:
np.fromfunction( lambda i,j :i==j ,(3,3))
                    

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
np.fromfunction(lambda i,j:i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [108]:
iterable1= (i*i for i in range(5))

In [109]:
np.fromiter(iterable1)

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [100]:
np.fromiter(iterable1,float)

array([ 0.,  1.,  4.,  9., 16.])

In [114]:
iterable1= (i*i for i in range(8))

In [115]:
np.fromiter(iterable1,int)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [119]:
np.fromstring("1234 45678",sep=" ")

array([ 1234., 45678.])

In [125]:
l=[2,3,4,5,6]

In [126]:
arr =np.array(l)

In [127]:
arr

array([2, 3, 4, 5, 6])

In [128]:
arr.ndim

1

In [130]:
l1 =[[1,2,3,4] ,[5,6,7,8]]

In [131]:
arr1=np.array(l1)

In [133]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [132]:
arr1.ndim

2

In [134]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])

In [135]:
arr3d.ndim

3

In [138]:
arr

array([2, 3, 4, 5, 6])

In [136]:
arr.size

5

In [142]:
arr.shape

(5,)

In [146]:
type(arr)
arr.dtype

dtype('int32')

In [139]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
arr1.size

8

In [143]:
arr1.shape

(2, 4)

In [147]:
arr1.dtype

dtype('int32')

In [140]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [141]:
arr3d.size

12

In [144]:
arr3d.shape

(2, 2, 3)

In [148]:
arr3d.dtype

dtype('int32')

In [242]:
np.array([(14,4.5,45),(23,45,66)])

array([[14. ,  4.5, 45. ],
       [23. , 45. , 66. ]])

In [149]:
arr22=np.array([(1.4,45,45),(23,45,66)])

In [150]:
arr22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [151]:
arr22.dtype

dtype('float64')

In [152]:
list(range(5))

[0, 1, 2, 3, 4]

In [153]:
list(range(0.5 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [155]:
np.arange(2.3 ,5.3)

array([2.3, 3.3, 4.3])

In [157]:
np.arange(2.3, 5.9 ,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9])

In [158]:
np.arange(2 ,5.3)

array([2., 3., 4., 5.])

In [160]:
list(np.arange(2 ,5.3, .3))

[2.0,
 2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998]

In [243]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [176]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [177]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [180]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [182]:
np.ones(3)

array([1., 1., 1.])

In [184]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [187]:
on =np.ones((2,3,2))

In [186]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [188]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [189]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [190]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [203]:
on*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [244]:
np.empty((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [205]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [206]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [207]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [209]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [211]:
np.logspace(2,4,20)

array([  100.        ,   127.42749857,   162.37767392,   206.91380811,
         263.66508987,   335.98182863,   428.13323987,   545.55947812,
         695.19279618,   885.86679041,  1128.83789168,  1438.44988829,
        1832.98071083,  2335.72146909,  2976.35144163,  3792.69019073,
        4832.93023857,  6158.48211066,  7847.59970351, 10000.        ])

In [222]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [224]:
np.random.randn(3,4)

array([[-0.57101175,  1.67047136,  0.85075341,  0.06307683],
       [-1.77878546,  1.45771549,  0.54089736, -0.191444  ],
       [-0.10747026,  1.59303328, -0.43507522, -0.6775361 ]])

In [225]:
arr =np.random.randn(3,4)

In [226]:
arr

array([[-1.40395661,  2.0440208 , -0.31652485,  1.19327346],
       [ 0.21293604,  1.02877834,  1.05658257, -0.60239357],
       [-0.82205606,  1.42091498, -0.60786728,  0.31243462]])

In [227]:
import pandas as pd

In [228]:
pd.DataFrame(arr)

0         1         2         3
0 -1.403957  2.044021 -0.316525  1.193273
1  0.212936  1.028778  1.056583 -0.602394
2 -0.822056  1.420915 -0.607867  0.312435

In [229]:
np.random.randn(3,4)

array([[ 0.59073796,  0.10115371, -0.95581007, -1.22781836],
       [-0.46934988, -1.69380903,  0.36122377,  1.16026577],
       [-0.42989464, -0.18529958, -1.2543228 , -0.64490483]])

In [231]:
np.random.randint(1,1000, (3,4))

array([[981, 448,  22, 453],
       [662, 686, 685, 796],
       [452, 245, 652, 656]])

In [232]:
pd.DataFrame(np.random.randint(1,1000, (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    512  453  577  534  546  219   42  781  448  192  ...  338  196  707   
1    221  801  169  220  842  897  605  940  243  530  ...  366  258  337   
2    320  689  562  994  479  178  275  179  536  461  ...  493  808  164   
3    584  459  432  328  205  659  972  778  339  528  ...  126  413   47   
4    561  820  161  580  136  538  801  967  235   72  ...  934  979  365   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  901  956  385  871  662  391  349  637  158  619  ...  250  975  474   
296  823  309  361  713  638  457   35  376  650  218  ...   56  117   53   
297  201  233   23  381  364  485  632  789  399  602  ...  804  637  369   
298  192   50  524  898  519  422  910  821  654  918  ...  545  237  997   
299   77  480  677  775  561  138   68   93  449  134  ...  741  861  964   

     393  394  395  396  397  398  399  
0    434  333  714  948  127  874  494  
1    886  480  527  813  179  726  207  
2    234  150  240  473  366  868  270  
3    904  272  984  109  938  729  329  
4    740  140  406  579  750  373  643  
..   ...  ...  ...  ...  ...  ...  ...  
295   56  575  366  838  494  616  107  
296  165   22  604  694  590  880   55  
297  448  155  299   59  800  591  963  
298  270   65  217    5  120  871  514  
299  910  404   31  131  636  933  826  

[300 rows x 400 columns]

In [233]:
pd.DataFrame(np.random.randint(1,1000, (300,400))).to_csv("read.csv")

In [234]:
arr

array([[-1.40395661,  2.0440208 , -0.31652485,  1.19327346],
       [ 0.21293604,  1.02877834,  1.05658257, -0.60239357],
       [-0.82205606,  1.42091498, -0.60786728,  0.31243462]])

In [245]:
arr.reshape(6,2)

array([[-1.40395661,  2.0440208 ],
       [-0.31652485,  1.19327346],
       [ 0.21293604,  1.02877834],
       [ 1.05658257, -0.60239357],
       [-0.82205606,  1.42091498],
       [-0.60786728,  0.31243462]])

In [246]:
arr.reshape(3,4)

array([[-1.40395661,  2.0440208 , -0.31652485,  1.19327346],
       [ 0.21293604,  1.02877834,  1.05658257, -0.60239357],
       [-0.82205606,  1.42091498, -0.60786728,  0.31243462]])

In [247]:
arr.reshape(4,3)

array([[-1.40395661,  2.0440208 , -0.31652485],
       [ 1.19327346,  0.21293604,  1.02877834],
       [ 1.05658257, -0.60239357, -0.82205606],
       [ 1.42091498, -0.60786728,  0.31243462]])

In [248]:
arr.reshape(2,6)

array([[-1.40395661,  2.0440208 , -0.31652485,  1.19327346,  0.21293604,
         1.02877834],
       [ 1.05658257, -0.60239357, -0.82205606,  1.42091498, -0.60786728,
         0.31243462]])

In [249]:
arr.reshape(1,12)

array([[-1.40395661,  2.0440208 , -0.31652485,  1.19327346,  0.21293604,
         1.02877834,  1.05658257, -0.60239357, -0.82205606,  1.42091498,
        -0.60786728,  0.31243462]])