In [1]:
import numpy as np

In [2]:
l =[1,2,3,4]

In [3]:
arr=np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
l1=[[1,2,3],[4,5,6]]

In [7]:
arr1=np.asarray(l1)

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
a=[1,2,4]
np.asanyarray(a)

array([1, 2, 4])

In [11]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [12]:
type(b)

numpy.matrix

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
a= np.asanyarray(l)

In [15]:
a

array([1, 2, 3, 4])

In [16]:
c=a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
c[0]=100                                                                                                            

In [19]:
a

array([100,   2,   3,   4])

In [20]:
c

array([100,   2,   3,   4])

In [21]:
d=np.copy(c)

In [22]:
d

array([100,   2,   3,   4])

In [23]:
d[2]=45

In [24]:
d

array([100,   2,  45,   4])

In [25]:
c

array([100,   2,   3,   4])

In [26]:
np.fromfunction( lambda i,j :i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
(lambda i,j :i==j ,(3,3))

(<function __main__.<lambda>(i, j)>, (3, 3))

In [28]:
np.fromfunction( lambda i,j :i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
np.fromfunction( lambda i,j :i==j ,(3,3))
                    

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j:i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable1= (i*i for i in range(5))

In [32]:
np.fromiter(iterable1)

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [ ]:
np.fromiter(iterable1,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
iterable1= (i*i for i in range(8))

In [ ]:
np.fromiter(iterable1,int)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [ ]:
np.fromstring("1234 45678",sep=" ")

array([ 1234., 45678.])

In [ ]:
l=[2,3,4,5,6]

In [ ]:
arr =np.array(l)

In [ ]:
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr.ndim

1

In [ ]:
l1 =[[1,2,3,4] ,[5,6,7,8]]

In [ ]:
arr1=np.array(l1)

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1.ndim

2

In [ ]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr.size

5

In [ ]:
arr.shape

(5,)

In [ ]:
type(arr)
arr.dtype

dtype('int32')

In [ ]:
3

3

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1.size

8

In [ ]:
arr1.shape

(2, 4)

In [ ]:
arr1.dtype

dtype('int32')

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.size

12

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.dtype

dtype('int32')

In [ ]:
np.array([(14,4.5,45),(23,45,66)])

array([[14. ,  4.5, 45. ],
       [23. , 45. , 66. ]])

In [ ]:
arr22=np.array([(1.4,45,45),(23,45,66)])

In [ ]:
arr22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [ ]:
arr22.dtype

dtype('float64')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(0.5 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(2.3 ,5.3)

array([2.3, 3.3, 4.3])

In [ ]:
np.arange(2.3, 5.9 ,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9])

In [ ]:
np.arange(2 ,5.3)

array([2., 3., 4., 5.])

In [ ]:
list(np.arange(2 ,5.3, .3))

[2.0,
 2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998]

In [ ]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
zero=np.zeros((3,3,3,2))

In [ ]:
zero

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
type(zero)

numpy.ndarray

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
on =np.ones((2,3,2))

In [ ]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
on*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [ ]:
np.empty((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.logspace(2,4,20)

array([  100.        ,   127.42749857,   162.37767392,   206.91380811,
         263.66508987,   335.98182863,   428.13323987,   545.55947812,
         695.19279618,   885.86679041,  1128.83789168,  1438.44988829,
        1832.98071083,  2335.72146909,  2976.35144163,  3792.69019073,
        4832.93023857,  6158.48211066,  7847.59970351, 10000.        ])

In [ ]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
np.random.randn(3,4)

array([[-0.2620002 ,  0.61568397,  0.83620521, -0.48589284],
       [ 1.68946572, -1.27583037, -0.94170128, -0.27129017],
       [-0.57737711,  0.6835194 ,  0.1023284 ,  3.26959348]])

In [34]:
arr =np.random.randn(3,4)

In [35]:
arr

array([[-2.14095881, -0.30184648,  2.17039886,  0.57944348],
       [-1.15652523,  0.30212193,  0.32250396,  0.12318569],
       [-1.71870648, -0.72284173,  0.90608951, -0.05189055]])

In [36]:
import pandas as pd

In [37]:
pd.DataFrame(arr)

0         1         2         3
0 -2.140959 -0.301846  2.170399  0.579443
1 -1.156525  0.302122  0.322504  0.123186
2 -1.718706 -0.722842  0.906090 -0.051891

In [38]:
np.random.randn(3,4)

array([[ 0.00942811,  0.21611247, -0.41181803, -0.82255849],
       [-1.63692495, -2.19980626,  0.33283814, -0.88931007],
       [-0.86933748, -0.16279782,  0.48288071,  1.16122767]])

In [39]:
np.random.randint(1,1000, (3,4))

array([[520, 160, 850, 338],
       [260, 396, 187, 847],
       [672, 516, 510,  91]])

In [40]:
pd.DataFrame(np.random.randint(1,1000, (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    558  991  627  665  558   25  101   11  876  225  ...   74   70   38   
1    842  268  258  705  902  610  233  945  563  787  ...  637  449  519   
2    565  333  991  129  120  957   56  461   88  322  ...  188  796  671   
3    936  463  155  741  358  634  446  978  660  370  ...  645  432  486   
4    848  444  714  443  300  303  776  275  303  171  ...  435  584  415   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  981  272  562  142  226  400  873    5  640  867  ...  950  385   88   
296  248  914  931  656   68  899  984  967  135   50  ...  405  958  980   
297  131  170  308   55  310  708  163  920  732  626  ...  387  196  148   
298  706  568  393  975  148  936  835  570  259  990  ...   40  721  456   
299  588  983  977  452  764  609  399  901  715  292  ...  570  172  176   

     393  394  395  396  397  398  399  
0    723  233  638  248  855  391  797  
1    241  596  683  312  421  298   16  
2     62  280  836    8  761  990  268  
3    808  773  737  448  497  846  608  
4    891  869  446  384  905  892  732  
..   ...  ...  ...  ...  ...  ...  ...  
295  569  403  701  644  474  808  355  
296  917  435  149  832  528  276  622  
297  349  460  856  987  315  176  878  
298   98    8  975  591  628  800  870  
299  180  705  399  619  532  164  194  

[300 rows x 400 columns]

In [ ]:
pd.DataFrame(np.random.randint(1,1000, (300,400))).to_csv("read.csv")

In [41]:
arr

array([[-2.14095881, -0.30184648,  2.17039886,  0.57944348],
       [-1.15652523,  0.30212193,  0.32250396,  0.12318569],
       [-1.71870648, -0.72284173,  0.90608951, -0.05189055]])

In [ ]:
arr.reshape(6,2)

array([[ 0.39944182, -0.78344889],
       [-0.54451945,  0.10812529],
       [-0.30091213, -1.72765264],
       [-0.50923635,  1.34685807],
       [-0.82513511, -0.67186183],
       [-0.50431227, -0.43902169]])

In [ ]:
arr.reshape(3,4)

array([[ 0.39944182, -0.78344889, -0.54451945,  0.10812529],
       [-0.30091213, -1.72765264, -0.50923635,  1.34685807],
       [-0.82513511, -0.67186183, -0.50431227, -0.43902169]])

In [42]:
arr.reshape(4,3)

array([[-2.14095881, -0.30184648,  2.17039886],
       [ 0.57944348, -1.15652523,  0.30212193],
       [ 0.32250396,  0.12318569, -1.71870648],
       [-0.72284173,  0.90608951, -0.05189055]])

In [43]:
arr.reshape(2,6)

array([[-2.14095881, -0.30184648,  2.17039886,  0.57944348, -1.15652523,
         0.30212193],
       [ 0.32250396,  0.12318569, -1.71870648, -0.72284173,  0.90608951,
        -0.05189055]])

In [44]:
arr.reshape(1,12)

array([[-2.14095881, -0.30184648,  2.17039886,  0.57944348, -1.15652523,
         0.30212193,  0.32250396,  0.12318569, -1.71870648, -0.72284173,
         0.90608951, -0.05189055]])

In [55]:
arr1 =np.random.randint(1,100 ,(6,7))

In [56]:
arr1

array([[61, 41, 57, 90, 16, 17,  9],
       [22, 71, 78, 33, 24, 74, 33],
       [21, 12, 67, 24, 31, 94, 28],
       [62, 55, 79, 16, 22, 97, 78],
       [30, 25, 48, 82,  4, 62, 56],
       [54, 58, 37, 25, 89, 78, 57]])

In [57]:
arr1[0:][2]

array([21, 12, 67, 24, 31, 94, 28])

In [58]:
arr1[2:5,-1]

array([28, 78, 56])

In [59]:
arr1[2:5,3]

array([24, 16, 82])

In [60]:
arr1[2,-1]

28

In [61]:
arr1[3][2:5]

array([79, 16, 22])

In [64]:
arr1[0:,0]

array([61, 22, 21, 62, 30, 54])

In [65]:
arr1>50

array([[ True, False,  True,  True, False, False, False],
       [False,  True,  True, False, False,  True, False],
       [False, False,  True, False, False,  True, False],
       [ True,  True,  True, False, False,  True,  True],
       [False, False, False,  True, False,  True,  True],
       [ True,  True, False, False,  True,  True,  True]])

In [66]:
arr1[arr1>50]

array([61, 57, 90, 71, 78, 74, 67, 94, 62, 55, 79, 97, 78, 82, 62, 56, 54,
       58, 89, 78, 57])

In [67]:
len(arr1[arr1>50])

21

In [69]:
arr1[arr1<50]

array([41, 16, 17,  9, 22, 33, 24, 33, 21, 12, 24, 31, 28, 16, 22, 30, 25,
       48,  4, 37, 25])

In [68]:
len(arr1[arr1<50])

21

In [70]:
arr1%2==0

array([[False, False, False,  True,  True, False, False],
       [ True, False,  True, False,  True,  True, False],
       [False,  True, False,  True, False,  True,  True],
       [ True, False, False,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False,  True, False]])

In [71]:
arr1[arr1%2==0]

array([90, 16, 22, 78, 24, 74, 12, 24, 94, 28, 62, 16, 22, 78, 30, 48, 82,
        4, 62, 56, 54, 58, 78])

In [72]:
arr1[arr1%2==1]

array([61, 41, 57, 17,  9, 71, 33, 33, 21, 67, 31, 55, 79, 97, 25, 37, 25,
       89, 57])

In [73]:
arr1[3:5]

array([[62, 55, 79, 16, 22, 97, 78],
       [30, 25, 48, 82,  4, 62, 56]])

In [81]:
arr1[3:5 ,2:4]

array([[79, 16],
       [48, 82]])

In [83]:
arr1[0][0]=1000

In [84]:
arr1

array([[1000,   41,   57,   90,   16,   17,    9],
       [  22,   71,   78,   33,   24,   74,   33],
       [  21,   12,   67,   24,   31,   94,   28],
       [  62,   55,   79,   16,   22,   97,   78],
       [  30,   25,   48,   82,    4,   62,   56],
       [  54,   58,   37,   25,   89,   78,   57]])

In [85]:
arr2 =np.random.randint(1,3 ,(3,3))
arr3 =np.random.randint(1,3 ,(3,3))

In [86]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [87]:
arr3

array([[2, 2, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [88]:
arr2+arr3

array([[3, 4, 3],
       [2, 3, 4],
       [3, 3, 3]])

In [89]:
arr2-arr3

array([[-1,  0, -1],
       [ 0,  1,  0],
       [-1, -1, -1]])

In [90]:
arr2*arr3

array([[2, 4, 2],
       [1, 2, 4],
       [2, 2, 2]])

In [91]:
arr2/arr3

array([[0.5, 1. , 0.5],
       [1. , 2. , 1. ],
       [0.5, 0.5, 0.5]])

In [92]:
arr2*arr3

array([[2, 4, 2],
       [1, 2, 4],
       [2, 2, 2]])

In [ ]:
# matrix multiplication

In [95]:
arr2@arr3

array([[ 6,  6,  8],
       [ 8,  8, 10],
       [ 5,  5,  6]])

In [96]:
arr2/0

C:\Users\PRASHANT\AppData\Local\Temp\ipykernel_6948\4133987296.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [97]:
arr2+100

array([[101, 102, 101],
       [101, 102, 102],
       [101, 101, 101]])

In [98]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [ ]:
#NUMPY-BROADCASTING

In [100]:
arr4 = np.zeros((4,4))

In [101]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
row = np.array([1,2,3,4])

In [103]:
row

array([1, 2, 3, 4])

In [104]:
arr4+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [105]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
# Column Wise Broadcasting
Col = np.array([[1,2,3,4]])

In [118]:
Col.T

array([[1],
       [2],
       [3],
       [4]])

In [119]:
display(Col.T+arr4)

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [120]:
arr5=np.random.randint(1,4 ,(3,4))

In [121]:
arr5

array([[1, 1, 3, 1],
       [2, 1, 1, 1],
       [1, 2, 1, 1]])

In [122]:
np.sqrt(arr5)

array([[1.        , 1.        , 1.73205081, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.        , 1.        ]])

In [123]:
np.log10(arr5)

array([[0.        , 0.        , 0.47712125, 0.        ],
       [0.30103   , 0.        , 0.        , 0.        ],
       [0.        , 0.30103   , 0.        , 0.        ]])

In [124]:
np.exp(arr5)

array([[ 2.71828183,  2.71828183, 20.08553692,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  7.3890561 ,  2.71828183,  2.71828183]])

In [127]:
np.iinfo

numpy.iinfo