In [12]:
import numpy as np

In [13]:
l =[1,2,3,4]

In [14]:
arr=np.array(l)

In [15]:
arr

array([1, 2, 3, 4])

In [16]:
type(arr)

numpy.ndarray

In [17]:
l1=[[1,2,3],[4,5,6]]

In [18]:
arr1=np.asarray(l1)

In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
type(arr1)

numpy.ndarray

In [21]:
a=[1,2,4]
np.asanyarray(a)

array([1, 2, 4])

In [22]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [23]:
type(b)

numpy.matrix

In [24]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [25]:
a= np.asanyarray(l)

In [26]:
a

array([1, 2, 3, 4])

In [27]:
c=a

In [28]:
c

array([1, 2, 3, 4])

In [44]:
c[0]=100                                                                                                            

In [30]:
a

array([100,   2,   3,   4])

In [31]:
c

array([100,   2,   3,   4])

In [32]:
d=np.copy(c)

In [33]:
d

array([100,   2,   3,   4])

In [34]:
d[2]=45

In [35]:
d

array([100,   2,  45,   4])

In [36]:
c

array([100,   2,   3,   4])

In [37]:
np.fromfunction( lambda i,j :i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
(lambda i,j :i==j ,(3,3))

(<function __main__.<lambda>(i, j)>, (3, 3))

In [39]:
np.fromfunction( lambda i,j :i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
np.fromfunction( lambda i,j :i==j ,(3,3))
                    

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [41]:
np.fromfunction(lambda i,j:i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [56]:
iterable1= (i*i for i in range(5))

In [45]:
np.fromiter(iterable1)

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [57]:
np.fromiter(iterable1,float)

array([ 0.,  1.,  4.,  9., 16.])

In [58]:
iterable1= (i*i for i in range(8))

In [59]:
np.fromiter(iterable1,int)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [49]:
np.fromstring("1234 45678",sep=" ")

array([ 1234., 45678.])

In [50]:
l=[2,3,4,5,6]

In [51]:
arr =np.array(l)

In [52]:
arr

array([2, 3, 4, 5, 6])

In [53]:
arr.ndim

1

In [60]:
l1 =[[1,2,3,4] ,[5,6,7,8]]

In [61]:
arr1=np.array(l1)

In [62]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
arr1.ndim

2

In [64]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])

In [70]:
arr3d.ndim

3

In [71]:
arr3d.shape

(2, 2, 3)

In [66]:
arr

array([2, 3, 4, 5, 6])

In [67]:
arr.size

5

In [68]:
arr.shape

(5,)

In [69]:
type(arr)
arr.dtype

dtype('int32')

In [72]:
3

3

In [73]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
arr1.size

8

In [75]:
arr1.shape

(2, 4)

In [76]:
arr1.dtype

dtype('int32')

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d.size

12

In [79]:
arr3d.shape

(2, 2, 3)

In [80]:
arr3d.dtype

dtype('int32')

In [81]:
np.array([(14,4.5,45),(23,45,66)])

array([[14. ,  4.5, 45. ],
       [23. , 45. , 66. ]])

In [82]:
arr22=np.array([(1.4,45,45),(23,45,66)])

In [83]:
arr22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [84]:
arr22.dtype

dtype('float64')

In [85]:
list(range(5))

[0, 1, 2, 3, 4]

In [86]:
list(range(0.5 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [87]:
np.arange(2.3 ,5.3)

array([2.3, 3.3, 4.3])

In [88]:
np.arange(2.3, 5.9 ,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9])

In [89]:
np.arange(2 ,5.3)

array([2., 3., 4., 5.])

In [90]:
list(np.arange(2 ,5.3, .3))

[2.0,
 2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998]

In [91]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [92]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [93]:
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [94]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [95]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [102]:
zero=np.zeros((3,3,3,2))

In [103]:
zero

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [104]:
type(zero)

numpy.ndarray

In [97]:
np.ones(3)

array([1., 1., 1.])

In [98]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
on =np.ones((2,3,2))

In [100]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [105]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [106]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [107]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [109]:
on*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [110]:
np.empty((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [111]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [112]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [113]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
np.logspace(2,4,20)

array([  100.        ,   127.42749857,   162.37767392,   206.91380811,
         263.66508987,   335.98182863,   428.13323987,   545.55947812,
         695.19279618,   885.86679041,  1128.83789168,  1438.44988829,
        1832.98071083,  2335.72146909,  2976.35144163,  3792.69019073,
        4832.93023857,  6158.48211066,  7847.59970351, 10000.        ])

In [116]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [117]:
np.random.randn(3,4)

array([[-0.2620002 ,  0.61568397,  0.83620521, -0.48589284],
       [ 1.68946572, -1.27583037, -0.94170128, -0.27129017],
       [-0.57737711,  0.6835194 ,  0.1023284 ,  3.26959348]])

In [118]:
arr =np.random.randn(3,4)

In [119]:
arr

array([[ 0.39944182, -0.78344889, -0.54451945,  0.10812529],
       [-0.30091213, -1.72765264, -0.50923635,  1.34685807],
       [-0.82513511, -0.67186183, -0.50431227, -0.43902169]])

In [120]:
import pandas as pd

In [121]:
pd.DataFrame(arr)

0         1         2         3
0  0.399442 -0.783449 -0.544519  0.108125
1 -0.300912 -1.727653 -0.509236  1.346858
2 -0.825135 -0.671862 -0.504312 -0.439022

In [122]:
np.random.randn(3,4)

array([[ 0.04891131, -0.29293836, -0.29370866, -0.10330059],
       [-0.36799478, -1.90157783, -0.42609722,  0.40991851],
       [-0.50393407, -0.45917772,  0.68823008, -0.22527438]])

In [123]:
np.random.randint(1,1000, (3,4))

array([[ 34,  65, 310, 514],
       [195, 554, 591, 555],
       [803, 320, 920, 451]])

In [124]:
pd.DataFrame(np.random.randint(1,1000, (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    139  549  559  474  463  878  326  269   16  880  ...  307  865  512   
1    268  157  866  817  797  455  628  444  415   21  ...  321  792   32   
2    848  818  331  630  448  295  361  179  827  205  ...  672   74  407   
3     87  272   81  499  181  543   89  709  135  631  ...  728  933  957   
4    191  434  967  933  279  863  998  778    8  696  ...  238  127  188   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  189  129  235  656  416   19  161  893  568  699  ...  613  933  399   
296  441  925  992  762  502   81  482  732  160  541  ...  462  954   76   
297  856  331  775  200  307  260  618   25  568   79  ...  864  299  802   
298  820  641  946  546  988   84  271  920  358  500  ...  577  620  255   
299  149  149   20  532  666  303  277  959  896  206  ...  497   80  822   

     393  394  395  396  397  398  399  
0    603  126  731  820  999  789  752  
1    561  551  755  209  553  547  938  
2    731  125  381   54  906  473   31  
3    232  761  562  979  245  645  367  
4    297  623  150  473  748  506   54  
..   ...  ...  ...  ...  ...  ...  ...  
295  433   45  849  566   86   35   11  
296  414  889  945  920  886  846   54  
297  592  703  350  601  800  979  523  
298  790  738  976  428  661  695  765  
299  730  664  901   34  432  504  258  

[300 rows x 400 columns]

In [125]:
pd.DataFrame(np.random.randint(1,1000, (300,400))).to_csv("read.csv")

In [126]:
arr

array([[ 0.39944182, -0.78344889, -0.54451945,  0.10812529],
       [-0.30091213, -1.72765264, -0.50923635,  1.34685807],
       [-0.82513511, -0.67186183, -0.50431227, -0.43902169]])

In [128]:
arr.reshape(6,2)

array([[ 0.39944182, -0.78344889],
       [-0.54451945,  0.10812529],
       [-0.30091213, -1.72765264],
       [-0.50923635,  1.34685807],
       [-0.82513511, -0.67186183],
       [-0.50431227, -0.43902169]])

In [127]:
arr.reshape(3,4)

array([[ 0.39944182, -0.78344889, -0.54451945,  0.10812529],
       [-0.30091213, -1.72765264, -0.50923635,  1.34685807],
       [-0.82513511, -0.67186183, -0.50431227, -0.43902169]])

In [129]:
arr.reshape(4,3)

array([[ 0.39944182, -0.78344889, -0.54451945],
       [ 0.10812529, -0.30091213, -1.72765264],
       [-0.50923635,  1.34685807, -0.82513511],
       [-0.67186183, -0.50431227, -0.43902169]])

In [130]:
arr.reshape(2,6)

array([[ 0.39944182, -0.78344889, -0.54451945,  0.10812529, -0.30091213,
        -1.72765264],
       [-0.50923635,  1.34685807, -0.82513511, -0.67186183, -0.50431227,
        -0.43902169]])

In [131]:
arr.reshape(1,12)

array([[ 0.39944182, -0.78344889, -0.54451945,  0.10812529, -0.30091213,
        -1.72765264, -0.50923635,  1.34685807, -0.82513511, -0.67186183,
        -0.50431227, -0.43902169]])